version: '3.9'

services:
  backend:
    build: ./backend
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  frontend:
    build: ./frontend/imgselect
    container_name: react-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/imgselect:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - backend
